function afficheDrapeau() {
//afficher le drapeau en fonction de l'indicatif téléphonique sélectionné
//definition du tableau d'objet
//{indicatif:'+1',pays:'Canada',fichier:'20px-Flag_of_Canada.svg.webp'},
const Indicatifs=[
{indicatif:'+1',pays:'États unis',fichier:'40px-Flag_of_the_United_States.svg.png'},
{indicatif:'+1',pays:'Canada',fichier:'40px-Flag_of_Canada.svg.png'},
{indicatif:'+1-242',pays:'Bahamas',fichier:'40px-Flag_of_the_Bahamas.svg.png'},
{indicatif:'+1-246',pays:'Barbade',fichier:'40px-Flag_of_Barbados.svg.png'},
{indicatif:'+1-264',pays:'Anguilla',fichier:'40px-Flag_of_Anguilla.svg.png'},
{indicatif:'+1-268',pays:'Antigua et barbuda',fichier:'40px-Flag_of_Antigua_and_Barbuda.svg.png'},
{indicatif:'+1-284',pays:'Vierges britanniques',fichier:'40px-Flag_of_the_British_Virgin_Islands.svg.png'},
{indicatif:'+1-340',pays:'Vierges des etats unis',fichier:'40px-Flag_of_the_United_States_Virgin_Islands.svg.png'},
{indicatif:'+1-345',pays:'Caïmans',fichier:'40px-Flag_of_the_Cayman_Islands.svg.png'},
{indicatif:'+1-441',pays:'Bermudes',fichier:'40px-Flag_of_Bermuda.svg.png'},
{indicatif:'+1-473',pays:'Grenade',fichier:'40px-Flag_of_Grenada.svg.png'},
{indicatif:'+1-649',pays:'Turques et Caïques',fichier:'40px-Flag_of_the_Turks_and_Caicos_Islands.svg.png'},
{indicatif:'+1-658',pays:'Jamaïque',fichier:'40px-Flag_of_Jamaica.svg.png'},
{indicatif:'+1-664',pays:'Montserrat',fichier:'40px-Flag_of_Montserrat.svg.png'},
{indicatif:'+1-670',pays:'Mariannes du nord',fichier:'40px-Flag_of_the_Northern_Mariana_Islands.svg.png'},
{indicatif:'+1-671',pays:'Guam',fichier:'40px-Flag_of_Guam.svg.png'},
{indicatif:'+1-684',pays:'Samoa américaines',fichier:'40px-Flag_of_American_Samoa.svg.png'},
{indicatif:'+1-721',pays:'Saint-Martin (royaume des Pays-Bas)',fichier:'40px-Flag_of_Sint_Maarten.svg.png'},
{indicatif:'+1-758',pays:'Sainte lucie',fichier:'40px-Flag_of_Saint_Lucia.svg.png'},
{indicatif:'+1-767',pays:'Dominique',fichier:'40px-Flag_of_Dominica.svg.png'},
{indicatif:'+1-784',pays:'Saint-Vincent-et-les-Grenadines',fichier:'40px-Flag_of_Saint_Vincent_and_the_Grenadines.svg.png'},
{indicatif:'+1-787',pays:'Porto Rico',fichier:'40px-Flag_of_Puerto_Rico.svg.png'},
{indicatif:'+1-939',pays:'Porto Rico',fichier:'40px-Flag_of_Puerto_Rico.svg.png'},
{indicatif:'+1-809',pays:'Dominicaine république',fichier:'40px-Flag_of_the_Dominican_Republic.svg.png'},
{indicatif:'+1-829',pays:'Dominicaine république',fichier:'40px-Flag_of_the_Dominican_Republic.svg.png'},
{indicatif:'+1-849',pays:'Dominicaine république',fichier:'40px-Flag_of_the_Dominican_Republic.svg.png'},
{indicatif:'+1-868',pays:'Trinite et tobago',fichier:'40px-Flag_of_Trinidad_and_Tobago.svg.png'},
{indicatif:'+1-869',pays:'Saint christophe et nieves',fichier:'40px-Flag_of_Saint_Kitts_and_Nevis.svg.png'},
{indicatif:'+1-876',pays:'Jamaïque',fichier:'40px-Flag_of_Jamaica.svg.png'},
{indicatif:'+20',pays:'Égypte',fichier:'40px-Flag_of_Egypt.svg.png'},
{indicatif:'+211',pays:'Soudan du Sud',fichier:'40px-Flag_of_South_Sudan.svg.png'},
{indicatif:'+212',pays:'Maroc',fichier:'40px-Flag_of_Morocco.svg.png'},
{indicatif:'+213',pays:'Algérie',fichier:'40px-Flag_of_Algeria.svg.png'},
{indicatif:'+216',pays:'Tunisie',fichier:'40px-Flag_of_Tunisia.svg.png'},
{indicatif:'+218',pays:'Libye',fichier:'40px-Flag_of_Libya.svg.png'},
{indicatif:'+220',pays:'Gambie',fichier:'40px-Flag_of_The_Gambia.svg.png'},
{indicatif:'+221',pays:'Sénégal',fichier:'40px-Flag_of_Senegal.svg.png'},
{indicatif:'+222',pays:'Mauritanie',fichier:'40px-Flag_of_Mauritania.svg.png'},
{indicatif:'+223',pays:'Mali',fichier:'40px-Flag_of_Mali.svg.png'},
{indicatif:'+224',pays:'Guinee',fichier:'40px-Flag_of_Guinea.svg.png'},
{indicatif:'+225',pays:'Côte divoire',fichier:'40px-Flag_of_Cote_dIvoire.svg.png'},
{indicatif:'+226',pays:'Burkina Faso',fichier:'40px-Flag_of_Burkina_Faso.svg.png'},
{indicatif:'+227',pays:'Niger',fichier:'40px-Flag_of_Niger.svg.png'},
{indicatif:'+228',pays:'Togo',fichier:'40px-Flag_of_Togo.svg.png'},
{indicatif:'+229',pays:'Bénin',fichier:'40px-Flag_of_Benin.svg.png'},
{indicatif:'+230',pays:'Maurice',fichier:'40px-Flag_of_Mauritius.svg.png'},
{indicatif:'+231',pays:'Liberia',fichier:'40px-Flag_of_Liberia.svg.png'},
{indicatif:'+232',pays:'Sierra Leone',fichier:'40px-Flag_of_Sierra_Leone.svg.png'},
{indicatif:'+233',pays:'Ghana',fichier:'40px-Flag_of_Ghana.svg.png'},
{indicatif:'+234',pays:'Nigeria',fichier:'40px-Flag_of_Nigeria.svg.png'},
{indicatif:'+235',pays:'Tchad',fichier:'40px-Flag_of_Chad.svg.png'},
{indicatif:'+236',pays:'Centrafricaine république',fichier:'40px-Flag_of_the_Central_African_Republic.svg.png'},
{indicatif:'+237',pays:'Cameroun',fichier:'40px-Flag_of_Cameroon.svg.png'},
{indicatif:'+238',pays:'Cap vert',fichier:'40px-Flag_of_Cape_Verde.svg.png'},
{indicatif:'+239',pays:'Sao tome et principe',fichier:'40px-Flag_of_Sao_Tome_and_Principe.svg.png'},
{indicatif:'+240',pays:'Guinee equatoriale',fichier:'40px-Flag_of_Equatorial_Guinea.svg.png'},
{indicatif:'+241',pays:'Gabon',fichier:'40px-Flag_of_Gabon.svg.png'},
{indicatif:'+242',pays:'Congo brazzaville',fichier:'40px-Flag_of_the_Republic_of_the_Congo.svg.png'},
{indicatif:'+243',pays:'Congo kinshasa',fichier:'40px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png'},
{indicatif:'+244',pays:'Angola',fichier:'40px-Flag_of_Angola.svg.png'},
{indicatif:'+245',pays:'Guinee bissau',fichier:'40px-Flag_of_Guinea-Bissau.svg.png'},
{indicatif:'+246',pays:'Territoire britannique océan indien',fichier:'40px-Flag_of_the_Commissioner_of_the_British_Indian_Ocean_Territory.svg.png'},
{indicatif:'+247',pays:'(île)Ascension',fichier:'40px-Flag_of_the_United_Kingdom.svg.png'},
{indicatif:'+248',pays:'Seychelles',fichier:'40px-Flag_of_Seychelles.svg.png'},
{indicatif:'+249',pays:'Soudan',fichier:'40px-Flag_of_Sudan.svg.png'},
{indicatif:'+250',pays:'Rwanda',fichier:'40px-Flag_of_Rwanda.svg.png'},
{indicatif:'+251',pays:'Éthiopie',fichier:'40px-Flag_of_Ethiopia.svg.png'},
{indicatif:'+252',pays:'Somalie',fichier:'40px-Flag_of_Somalia.svg.png'},
{indicatif:'+253',pays:'Djibouti',fichier:'40px-Flag_of_Djibouti.svg.png'},
{indicatif:'+254',pays:'Kenya',fichier:'40px-Flag_of_Kenya.svg.png'},
{indicatif:'+255',pays:'Tanzanie',fichier:'40px-Flag_of_Tanzania.svg.png'},
{indicatif:'+256',pays:'Ouganda',fichier:'40px-Flag_of_Uganda.svg.png'},
{indicatif:'+257',pays:'Burundi',fichier:'40px-Flag_of_Burundi.svg.png'},
{indicatif:'+258',pays:'Mozambique',fichier:'40px-Flag_of_Mozambique.svg.png'},
{indicatif:'+260',pays:'Zambie',fichier:'40px-Flag_of_Zambia.svg.png'},
{indicatif:'+261',pays:'Madagascar',fichier:'40px-Flag_of_Madagascar.svg.png'},
{indicatif:'+262',pays:'Reunion',fichier:'40px-Flag_of_Reunion.svg.png'},
{indicatif:'+263',pays:'Zimbabwe',fichier:'40px-Flag_of_Zimbabwe.svg.png'},
{indicatif:'+264',pays:'Namibie',fichier:'40px-Flag_of_Namibia.svg.png'},
{indicatif:'+265',pays:'Malawi',fichier:'40px-Flag_of_Malawi.svg.png'},
{indicatif:'+266',pays:'Lesotho',fichier:'40px-Flag_of_Lesotho.svg.png'},
{indicatif:'+267',pays:'Botswana',fichier:'40px-Flag_of_Botswana.svg.png'},
{indicatif:'+268',pays:'Eswatini',fichier:'40px-Flag_of_Eswatini.svg.png'},
{indicatif:'+269',pays:'Comores',fichier:'40px-Flag_of_the_Comoros.svg.png'},
{indicatif:'+27',pays:'Afrique du Sud',fichier:'40px-Flag_of_South_Africa.svg.png'},
{indicatif:'+290',pays:'Sainte-Hélène',fichier:'40px-Flag_of_Saint_Helena.svg.png'},
{indicatif:'+291',pays:'Erythree',fichier:'40px-Flag_of_Eritrea.svg.png'},
{indicatif:'+297',pays:'Aruba',fichier:'40px-Flag_of_Aruba.svg.png'},
{indicatif:'+298',pays:'Féroé',fichier:'40px-Flag_of_the_Faroe_Islands.svg.png'},
{indicatif:'+299',pays:'Groenland',fichier:'40px-Flag_of_Greenland.svg.png'},
{indicatif:'+30',pays:'Grece',fichier:'40px-Flag_of_Greece.svg.png'},
{indicatif:'+31',pays:'Pays bas',fichier:'40px-Flag_of_the_Netherlands.svg.png'},
{indicatif:'+32',pays:'Belgique',fichier:'40px-Flag_of_Belgium_civil.svg.png'},
{indicatif:'+33',pays:'France',fichier:'40px-Flag_of_France.svg.png'},
{indicatif:'+34',pays:'Espagne',fichier:'40px-Flag_of_Spain.svg.png'},
{indicatif:'+350',pays:'Gibraltar',fichier:'40px-Flag_of_Gibraltar.svg.png'},
{indicatif:'+351',pays:'Portugal',fichier:'40px-Flag_of_Portugal.svg.png'},
{indicatif:'+352',pays:'Luxembourg',fichier:'40px-Flag_of_Luxembourg.svg.png'},
{indicatif:'+353',pays:'Irlande',fichier:'40px-Flag_of_Ireland.svg.png'},
{indicatif:'+354',pays:'Islande',fichier:'40px-Flag_of_Iceland.svg.png'},
{indicatif:'+355',pays:'Albanie',fichier:'40px-Flag_of_Albania.svg.png'},
{indicatif:'+356',pays:'Malte',fichier:'40px-Flag_of_Malta.svg.png'},
{indicatif:'+357',pays:'Chypre',fichier:'40px-Flag_of_Cyprus.svg.png'},
{indicatif:'+358',pays:'Finlande',fichier:'40px-Flag_of_Finland.svg.png'},
{indicatif:'+359',pays:'Bulgarie',fichier:'40px-Flag_of_Bulgaria.svg.png'},
{indicatif:'+36',pays:'Hongrie',fichier:'40px-Flag_of_Hungary.svg.png'},
{indicatif:'+370',pays:'Lituanie',fichier:'40px-Flag_of_Lithuania.svg.png'},
{indicatif:'+371',pays:'Lettonie',fichier:'40px-Flag_of_Latvia.svg.png'},
{indicatif:'+372',pays:'Estonie',fichier:'40px-Flag_of_Estonia.svg.png'},
{indicatif:'+373',pays:'Moldavie',fichier:'40px-Flag_of_Moldova.svg.png'},
{indicatif:'+374',pays:'Arménie',fichier:'40px-Flag_of_Armenia.svg.png'},
{indicatif:'+375',pays:'Bielorussie',fichier:'40px-Flag_of_Belarus.svg.png'},
{indicatif:'+376',pays:'Andorre',fichier:'40px-Flag_of_Andorra.svg.png'},
{indicatif:'+377',pays:'Monaco',fichier:'40px-Flag_of_Monaco.svg.png'},
{indicatif:'+378',pays:'Saint marin',fichier:'40px-Flag_of_San_Marino.svg.png'},
{indicatif:'+379',pays:'Vatican',fichier:'18px-Flag_of_the_Vatican_City.svg.png'},
{indicatif:'+380',pays:'Ukraine',fichier:'40px-Flag_of_Ukraine.svg.png'},
{indicatif:'+381',pays:'Serbie',fichier:'40px-Flag_of_Serbia.svg.png'},
{indicatif:'+382',pays:'Montenegro',fichier:'40px-Flag_of_Montenegro.svg.png'},
{indicatif:'+383',pays:'Kosovo',fichier:'40px-Flag_of_Kosovo.svg.png'},
{indicatif:'+385',pays:'Croatie',fichier:'40px-Flag_of_Croatia.svg.png'},
{indicatif:'+386',pays:'Slovénie',fichier:'40px-Flag_of_Slovenia.svg.png'},
{indicatif:'+387',pays:'Bosnie-Herzégovine',fichier:'40px-Flag_of_Bosnia_and_Herzegovina.svg.png'},
{indicatif:'+389',pays:'Macédoine du Nord',fichier:'40px-Flag_of_North_Macedonia.svg.png'},
{indicatif:'+39',pays:'Italie',fichier:'40px-Flag_of_Italy.svg.png'},
{indicatif:'+40',pays:'Roumanie',fichier:'40px-Flag_of_Romania.svg.png'},
{indicatif:'+41',pays:'Suisse',fichier:'15px-Flag_of_Switzerland.svg.png'},
{indicatif:'+420',pays:'Tchéquie',fichier:'40px-Flag_of_the_Czech_Republic.svg.png'},
{indicatif:'+421',pays:'Slovaquie',fichier:'40px-Flag_of_Slovakia.svg.png'},
{indicatif:'+423',pays:'Liechtenstein',fichier:'40px-Flag_of_Liechtenstein.svg.png'},
{indicatif:'+43',pays:'Autriche',fichier:'40px-Flag_of_Austria.svg.png'},
{indicatif:'+44',pays:'Royaume uni',fichier:'40px-Flag_of_the_United_Kingdom.svg.png'},
{indicatif:'+45',pays:'Danemark',fichier:'40px-Flag_of_Denmark.svg.png'},
{indicatif:'+46',pays:'Suède',fichier:'40px-Flag_of_Sweden.svg.png'},
{indicatif:'+47',pays:'Norvege',fichier:'40px-Flag_of_Norway.svg.png'},
{indicatif:'+48',pays:'Pologne',fichier:'40px-Flag_of_Poland.svg.png'},
{indicatif:'+49',pays:'Allemagne',fichier:'40px-Flag_of_Germany.svg.png'},
{indicatif:'+500',pays:'Malouines',fichier:'40px-Flag_of_the_Falkland_Islands.svg.png'},
{indicatif:'+501',pays:'Belize',fichier:'40px-Flag_of_Belize.svg.png'},
{indicatif:'+502',pays:'Guatemala',fichier:'40px-Flag_of_Guatemala.svg.png'},
{indicatif:'+503',pays:'Salvador',fichier:'40px-Flag_of_El_Salvador.svg.png'},
{indicatif:'+504',pays:'Honduras',fichier:'40px-Flag_of_Honduras.svg.png'},
{indicatif:'+505',pays:'Nicaragua',fichier:'40px-Flag_of_Nicaragua.svg.png'},
{indicatif:'+506',pays:'Costa Rica',fichier:'40px-Flag_of_Costa_Rica.svg.png'},
{indicatif:'+507',pays:'Panama',fichier:'40px-Flag_of_Panama.svg.png'},
{indicatif:'+508',pays:'Saint pierre et miquelon',fichier:'40px-Flag_of_France.svg.png'},
{indicatif:'+509',pays:'Haïti',fichier:'40px-Flag_of_Haiti.svg.png'},
{indicatif:'+51',pays:'Perou',fichier:'40px-Flag_of_Peru.svg.png'},
{indicatif:'+52',pays:'Mexique',fichier:'40px-Flag_of_Mexico.svg.png'},
{indicatif:'+53',pays:'Cuba',fichier:'40px-Flag_of_Cuba.svg.png'},
{indicatif:'+54',pays:'Argentine',fichier:'40px-Flag_of_Argentina.svg.png'},
{indicatif:'+55',pays:'Bresil',fichier:'40px-Flag_of_Brazil.svg.png'},
{indicatif:'+56',pays:'Chili',fichier:'40px-Flag_of_Chile.svg.png'},
{indicatif:'+57',pays:'Colombie',fichier:'40px-Flag_of_Colombia.svg.png'},
{indicatif:'+58',pays:'Venezuela',fichier:'40px-Flag_of_Venezuela.svg.png'},
{indicatif:'+590',pays:'Guadeloupe',fichier:'40px-Flag_of_France.svg.png'},
{indicatif:'+591',pays:'Bolivie',fichier:'40px-Flag_of_Bolivia.svg.png'},
{indicatif:'+592',pays:'Guyana',fichier:'40px-Flag_of_Guyana.svg.png'},
{indicatif:'+593',pays:'Équateur',fichier:'40px-Flag_of_Ecuador.svg.png'},
{indicatif:'+594',pays:'Guyane',fichier:'40px-Flag_of_France.svg.png'},
{indicatif:'+595',pays:'Paraguay',fichier:'40px-Flag_of_Paraguay.svg.png'},
{indicatif:'+596',pays:'Martinique',fichier:'40px-Flag_of_France.svg.png'},
{indicatif:'+597',pays:'Suriname',fichier:'40px-Flag_of_Suriname.svg.png'},
{indicatif:'+598',pays:'Uruguay',fichier:'40px-Flag_of_Uruguay.svg.png'},
{indicatif:'+599',pays:'Curaçao',fichier:'40px-Flag_of_Curacao.svg.png'},
{indicatif:'+60',pays:'Malaisie',fichier:'40px-Flag_of_Malaysia.svg.png'},
{indicatif:'+61',pays:'Australie',fichier:'40px-Flag_of_Australia.svg.png'},
{indicatif:'+62',pays:'Indonesie',fichier:'40px-Flag_of_Indonesia.svg.png'},
{indicatif:'+63',pays:'Philippines',fichier:'40px-Flag_of_the_Philippines.svg.png'},
{indicatif:'+64',pays:'Nouvelle zélande',fichier:'40px-Flag_of_New_Zealand.svg.png'},
{indicatif:'+65',pays:'Singapour',fichier:'40px-Flag_of_Singapore.svg.png'},
{indicatif:'+66',pays:'Thaïlande',fichier:'40px-Flag_of_Thailand.svg.png'},
{indicatif:'+670',pays:'Timor-Leste',fichier:'40px-Flag_of_East_Timor.svg.png'},
{indicatif:'+673',pays:'Brunei',fichier:'40px-Flag_of_Brunei.svg.png'},
{indicatif:'+674',pays:'Nauru',fichier:'40px-Flag_of_Nauru.svg.png'},
{indicatif:'+675',pays:'Papouasie nouvelle guinée',fichier:'40px-Flag_of_Papua_New_Guinea.svg.png'},
{indicatif:'+676',pays:'Tonga',fichier:'40px-Flag_of_Tonga.svg.png'},
{indicatif:'+677',pays:'Salomon',fichier:'40px-Flag_of_the_Solomon_Islands.svg.png'},
{indicatif:'+678',pays:'Vanuatu',fichier:'40px-Flag_of_Vanuatu.svg.png'},
{indicatif:'+679',pays:'Fidji',fichier:'40px-Flag_of_Fiji.svg.png'},
{indicatif:'+680',pays:'Palaos',fichier:'40px-Flag_of_Palau.svg.png'},
{indicatif:'+681',pays:'Wallis et Futuna',fichier:'40px-Flag_of_Wallis_and_Futuna.svg.png'},
{indicatif:'+682',pays:'Cook',fichier:'40px-Flag_of_the_Cook_Islands.svg.png'},
{indicatif:'+683',pays:'Niue',fichier:'40px-Flag_of_Niue.svg.png'},
{indicatif:'+685',pays:'Samoa',fichier:'40px-Flag_of_Samoa.svg.png'},
{indicatif:'+686',pays:'Kiribati',fichier:'40px-Flag_of_Kiribati.svg.png'},
{indicatif:'+687',pays:'Nouvelle calédonie',fichier:'40px-Flags_of_New_Caledonia.svg.png'},
{indicatif:'+688',pays:'Tuvalu',fichier:'40px-Flag_of_Tuvalu.svg.png'},
{indicatif:'+689',pays:'Polynesie francaise',fichier:'40px-Flag_of_French_Polynesia.svg.png'},
{indicatif:'+690',pays:'Tokelau',fichier:'40px-Flag_of_Tokelau.svg.png'},
{indicatif:'+691',pays:'Micronesie',fichier:'40px-Flag_of_the_Federated_States_of_Micronesia.svg.png'},
{indicatif:'+692',pays:'Marshall iles',fichier:'40px-Flag_of_the_Marshall_Islands.svg.png'},
{indicatif:'+7',pays:'Kazakhstan',fichier:'40px-Flag_of_Kazakhstan.svg.png'},
{indicatif:'+7',pays:'Russie',fichier:'40px-Flag_of_Russia.svg.png'},
{indicatif:'+81',pays:'Japon',fichier:'40px-Flag_of_Japan.svg.png'},
{indicatif:'+82',pays:'Corée du Sud',fichier:'40px-Flag_of_South_Korea.svg.png'},
{indicatif:'+84',pays:'Viet nam',fichier:'40px-Flag_of_Vietnam.svg.png'},
{indicatif:'+850',pays:'Corée du Nord',fichier:'40px-Flag_of_North_Korea.svg.png'},
{indicatif:'+852',pays:'Hong Kong',fichier:'40px-Flag_of_Hong_Kong.svg.png'},
{indicatif:'+853',pays:'Macao',fichier:'40px-Flag_of_Macau.svg.png'},
{indicatif:'+855',pays:'Cambodge',fichier:'40px-Flag_of_Cambodia.svg.png'},
{indicatif:'+856',pays:'Laos',fichier:'40px-Flag_of_Laos.svg.png'},
{indicatif:'+86',pays:'Chine',fichier:'40px-Flag_of_the_Peoples_Republic_of_China.svg.png'},
{indicatif:'+880',pays:'Bangladesh',fichier:'40px-Flag_of_Bangladesh.svg.png'},
{indicatif:'+886',pays:'Taiwan',fichier:'40px-Flag_of_the_Republic_of_China.svg.png'},
{indicatif:'+90',pays:'Turquie',fichier:'40px-Flag_of_Turkey.svg.png'},
{indicatif:'+91',pays:'Inde',fichier:'40px-Flag_of_India.svg.png'},
{indicatif:'+92',pays:'Pakistan',fichier:'40px-Flag_of_Pakistan.svg.png'},
{indicatif:'+93',pays:'Afghanistan',fichier:'40px-Flag_of_the_Taliban.svg.png'},
{indicatif:'+94',pays:'Sri Lanka',fichier:'40px-Flag_of_Sri_Lanka.svg.png'},
{indicatif:'+95',pays:'Birmanie',fichier:'40px-Flag_of_Myanmar.svg.png'},
{indicatif:'+960',pays:'Maldives',fichier:'40px-Flag_of_Maldives.svg.png'},
{indicatif:'+961',pays:'Liban',fichier:'40px-Flag_of_Lebanon.svg.png'},
{indicatif:'+962',pays:'Jordanie',fichier:'40px-Flag_of_Jordan.svg.png'},
{indicatif:'+963',pays:'Syrie',fichier:'40px-Flag_of_Syria.svg.png'},
{indicatif:'+964',pays:'Irak',fichier:'40px-Flag_of_Iraq.svg.png'},
{indicatif:'+965',pays:'Koweit',fichier:'40px-Flag_of_Kuwait.svg.png'},
{indicatif:'+966',pays:'Arabie saoudite',fichier:'40px-Flag_of_Saudi_Arabia.svg.png'},
{indicatif:'+967',pays:'Yemen',fichier:'40px-Flag_of_Yemen.svg.png'},
{indicatif:'+968',pays:'Oman',fichier:'40px-Flag_of_Oman.svg.png'},
{indicatif:'+970',pays:'palestine',fichier:'40px-Flag_of_Palestine.svg.png'},
{indicatif:'+971',pays:'Émirats arabes unis',fichier:'40px-Flag_of_the_United_Arab_Emirates.svg.png'},
{indicatif:'+972',pays:'Israël',fichier:'40px-Flag_of_Israel.svg.png'},
{indicatif:'+973',pays:'Bahreïn',fichier:'40px-Flag_of_Bahrain.svg.png'},
{indicatif:'+974',pays:'Qatar',fichier:'40px-Flag_of_Qatar.svg.png'},
{indicatif:'+975',pays:'Bhoutan',fichier:'40px-Flag_of_Bhutan.svg.png'},
{indicatif:'+976',pays:'Mongolie',fichier:'40px-Flag_of_Mongolia.svg.png'},
{indicatif:'+977',pays:'Nepal',fichier:'15px-Flag_of_Nepal.svg.png'},
{indicatif:'+98',pays:'Iran',fichier:'40px-Flag_of_Iran.svg.png'},
{indicatif:'+992',pays:'Tadjikistan',fichier:'40px-Flag_of_Tajikistan.svg.png'},
{indicatif:'+993',pays:'Turkménistan',fichier:'40px-Flag_of_Turkmenistan.svg.png'},
{indicatif:'+994',pays:'Azerbaidjan',fichier:'40px-Flag_of_Azerbaijan.svg.png'},
{indicatif:'+995',pays:'Georgie',fichier:'40px-Flag_of_Georgia.svg.png'},
{indicatif:'+996',pays:'Kirghizistan',fichier:'40px-Flag_of_Kyrgyzstan.svg.png'},
{indicatif:'+998',pays:'Ouzbékistan',fichier:'40px-Flag_of_Uzbekistan.svg.png'},
];
var basedir='./images/drapeaux/';
// Get the index of the object in the array
const indexOfObject = Indicatifs.findIndex((obj) => {
  // if the current object name key matches the string
  // return boolean value true
  if (obj.indicatif === document.getElementById('indicatif').value) {
	//alert (document.getElementById('indicatif').value);
    return true;
  }
  // else return boolean value false
  return false;
});
//alert ('findIndex:'+indexOfObject+' fichier:'+Indicatifs[indexOfObject].fichier);
if (indexOfObject> -1) {
	document.getElementById('drapeau').src=basedir+Indicatifs[indexOfObject].fichier;
}
else{
	document.getElementById('drapeau').src=basedir;
}
}
//gerer le changement de l'indicatif téléphonique
document.getElementById('indicatif').addEventListener('change',afficheDrapeau);